// Import required modules from Sequelize
import { DataTypes, Model, Optional } from "sequelize";
import sequelize from "../db";   // Import the Sequelize instance
import User from "./User";       // Import the User model for relationship

// ------------------------
// 1. Define TypeScript interfaces for the model
// ------------------------

// Attributes that exist in the Order table
interface OrderAttributes {
  id: number;       // Primary key
  userId: number;   // Foreign key to the User table
}

// Attributes required when creating a new Order
// `id` is optional because it will be auto-generated by the database
interface OrderCreationAttributes extends Optional<OrderAttributes, "id"> {}

// ------------------------
// 2. Define the Order class
// ------------------------

// Extend Sequelize's Model class with TypeScript typing
// OrderAttributes = full model fields
// OrderCreationAttributes = fields required when creating a new instance
class Order extends Model<OrderAttributes, OrderCreationAttributes>
  implements OrderAttributes {
  public id!: number;       // Primary key, will always exist
  public userId!: number;   // Foreign key, will always exist
}

// ------------------------
// 3. Initialize the Order model
// ------------------------

Order.init(
  {
    // Define the `id` column
    id: {
      type: DataTypes.INTEGER,  // Integer type
      primaryKey: true,         // Primary key
      autoIncrement: true       // Auto-increment the value
    },
    // Define the `userId` column (foreign key to users table)
    userId: {
      type: DataTypes.INTEGER,  // Integer type
      allowNull: false          // Cannot be null
    }
  },
  {
    sequelize,                  // Link this model to our Sequelize instance
    tableName: "orders",        // Table name in DB
    indexes: [{ fields: ["userId"] }]  // Create an index on userId for faster queries
  }
);

// ------------------------
// 4. Define relationships
// ------------------------

// Each Order belongs to one User (foreign key = userId)
Order.belongsTo(User, { foreignKey: "userId" });

// Each User can have many Orders (foreign key = userId)
User.hasMany(Order, { foreignKey: "userId" });

// ------------------------
// 5. Export the Order model
// ------------------------
export default Order;
