// Import required modules from Sequelize
import { DataTypes, Model, Optional } from "sequelize";  
import sequelize from "../db";  // Import the Sequelize instance you created in db.ts

// ------------------------
// 1. Define TypeScript interfaces for the model
// ------------------------

// Attributes that exist in the User table
interface UserAttributes {
  id: number;      // Primary key
  name: string;    // User's name
}

// Attributes required when creating a new User
// `id` is optional because it will be auto-generated by the database
interface UserCreationAttributes extends Optional<UserAttributes, "id"> {}

// ------------------------
// 2. Define the User class
// ------------------------

// Extend Sequelize's Model class with TypeScript typing
// UserAttributes = full model fields
// UserCreationAttributes = fields required when creating a new instance
class User extends Model<UserAttributes, UserCreationAttributes>
  implements UserAttributes {
  public id!: number;    // Primary key, will always exist
  public name!: string;  // User name, will always exist
}

// ------------------------
// 3. Initialize the User model
// ------------------------

User.init(
  {
    // Define the `id` column
    id: {
      type: DataTypes.INTEGER,  // Integer type
      primaryKey: true,         // Primary key
      autoIncrement: true       // Auto-increment the value
    },
    // Define the `name` column
    name: {
      type: DataTypes.STRING,   // String type
      allowNull: false          // Cannot be null
    }
  },
  {
    sequelize,                  // Link this model to our Sequelize instance
    tableName: "users"          // Specify the table name in the database
    // Other options like timestamps (createdAt/updatedAt) default to true
  }
);

// Export the User model for use in other parts of the app
export default User;
